import { Bootstrap } from "./../src/interfaces";

export const mockData: Bootstrap = {
  element_stats: [
    { label: "Goals scored", name: "goals_scored" },
    { label: "Assists", name: "assists" },
  ],
  element_types: [
    {
      id: 1,
      plural_name: "Goalkeepers",
      plural_name_short: "GKP",
      singular_name: "Goalkeeper",
      singular_name_short: "GKP",
      squad_max_play: 1,
      squad_min_play: 1,
      squad_select: 2,
      sub_positions_locked: [],
      ui_shirt_specific: false,
      element_count: 2,
    },
  ],
  elements: [
    {
      assists: 0,
      bonus: 0,
      bps: 0,
      chance_of_playing_next_round: null,
      chance_of_playing_this_round: null,
      clean_sheets: 0,
      code: 1,
      corners_and_indirect_freekicks_order: null,
      corners_and_indirect_freekicks_text: "",
      cost_change_event_fall: 0,
      cost_change_event: 0,
      cost_change_start_fall: 0,
      cost_change_start: 0,
      creativity: "",
      creativity_rank_type: null,
      creativity_rank: null,
      direct_freekicks_order: null,
      direct_freekicks_text: "",
      dreamteam_count: 0,
      element_type: 1,
      ep_next: null,
      ep_this: null,
      event_points: 0,
      first_name: "John",
      form: "",
      goals_conceded: 0,
      goals_scored: 0,
      ict_index: "",
      ict_index_rank_type: null,
      ict_index_rank: null,
      id: 1,
      in_dreamteam: false,
      influence: "",
      influence_rank_type: null,
      influence_rank: null,
      minutes: 0,
      news_added: null,
      news: "",
      now_cost: 50,
      own_goals: 0,
      penalties_missed: 0,
      penalties_order: null,
      penalties_saved: 0,
      penalties_text: "",
      photo: "",
      points_per_game: "",
      red_cards: 0,
      saves: 0,
      second_name: "Doe",
      selected_by_percent: "",
      special: false,
      squad_number: null,
      status: "a",
      team_code: 1,
      team: 1,
      threat: "",
      threat_rank_type: null,
      threat_rank: null,
      total_points: 0,
      transfers_in_event: 0,
      transfers_in: 0,
      transfers_out_event: 0,
      transfers_out: 0,
      value_form: "",
      value_season: "",
      web_name: "Doe",
      yellow_cards: 0,
    },
  ],
  events: [
    {
      average_entry_score: 0,
      chip_plays: [],
      data_checked: false,
      deadline_time: "",
      deadline_time_epoch: 0,
      deadline_time_game_offset: 0,
      finished: false,
      highest_score: null,
      highest_scoring_entry: null,
      id: 1,
      is_current: false,
      is_next: false,
      is_previous: false,
      most_captained: null,
      most_selected: null,
      most_transferred_in: null,
      most_vice_captained: null,
      name: "Gameweek 1",
      top_element: null,
      top_element_info: null,
      transfers_made: 0,
      cup_leagues_created: false,
      h2h_ko_matches_created: false,
    },
  ],
  game_settings: {
    cup_start_event_id: null,
    league_join_private_max: 0,
    league_join_public_max: 0,
    league_max_ko_rounds_private_h2h: 0,
    league_max_size_private_h2h: 0,
    league_max_size_public_classic: 0,
    league_max_size_public_h2h: 0,
    league_points_h2h_draw: 0,
    league_points_h2h_lose: 0,
    league_points_h2h_win: 0,
    league_prefix_public: "",
    squad_squadplay: 0,
    squad_squadsize: 0,
    squad_team_limit: 0,
    squad_total_spend: 0,
    stats_form_days: 0,
    sys_vice_captain_enabled: false,
    timezone: "",
    transfers_sell_on_fee: 0,
    ui_currency_multiplier: 0,
    ui_special_shirt_exclusions: [],
    ui_use_special_shirts: false,
    league_h2h_tiebreak_stats: ["+goals_scored", "-goals_conceded"],
    transfers_cap: 0,
    cup_qualifying_method: null,
    cup_stop_event_id: null,
    cup_type: null,
    league_ko_first_instead_of_random: false,
  },
  phases: [
    {
      id: 1,
      name: "Phase 1",
      start_event: 1,
      stop_event: 1,
    },
  ],
  teams: [
    {
      code: 1,
      draw: 0,
      form: null,
      id: 1,
      loss: 0,
      name: "Team 1",
      played: 0,
      points: 0,
      position: 0,
      pulse_id: 0,
      short_name: "T1",
      strength: 0,
      strength_attack_away: 0,
      strength_attack_home: 0,
      strength_defence_away: 0,
      strength_defence_home: 0,
      strength_overall_away: 0,
      strength_overall_home: 0,
      team_division: null,
      unavailable: false,
      win: 0,
    },
  ],
  total_players: 0,
};
